import { createFileRoute, Link } from "@tanstack/react-router";
import { Shield, Lock, Eye, FileText, ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Lens Master" },
      {
        name: "description",
        content:
          "Learn how Lens Master collects, protects, and uses your personal and prescription eyewear data.",
      },
      { property: "og:title", content: "Privacy Policy — Lens Master" },
      {
        property: "og:description",
        content: "Transparent and secure privacy practices for Lens Master customers.",
      },
      { property: "og:url", content: "/privacy-policy" },
    ],
    links: [{ rel: "canonical", href: "/privacy-policy" }],
  }),
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-4xl px-5 sm:px-6 md:px-8 pt-8 sm:pt-14 md:pt-20 pb-16 sm:pb-24">
      <Link
        to="/"
        className="inline-flex items-center gap-1.5 text-[12px] uppercase tracking-wider text-muted-foreground hover:text-foreground transition-colors mb-6"
      >
        <ArrowLeft className="h-3.5 w-3.5" strokeWidth={1.5} />
        Back to Home
      </Link>

      <div className="border-b pb-8">
        <p className="text-[10px] sm:text-xs uppercase tracking-[0.3em] text-muted-foreground">
          Legal &amp; Privacy
        </p>
        <h1 className="mt-3 font-display text-4xl sm:text-5xl font-light tracking-tight">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: August 2026 · Lens Master by The Swadesh, Jaipur, India
        </p>
      </div>

      <div className="mt-10 space-y-10 text-muted-foreground text-sm sm:text-base leading-relaxed">
        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal flex items-center gap-2.5">
            <Shield className="h-5 w-5 text-gold" strokeWidth={1.5} />
            1. Introduction
          </h2>
          <p>
            Welcome to <strong>Lens Master</strong> (operated by The Swadesh, located at B-51,
            Lal Kothi Shopping Centre, Jaipur, Rajasthan 302015). We are committed to protecting
            your privacy and handling your personal data, contact information, and optical
            prescription details with utmost care, security, and transparency.
          </p>
          <p>
            This Privacy Policy explains what information we collect, how we use it to fulfill your
            eyewear orders, and your rights regarding your data when using our website (
            <span className="font-mono text-xs">lensmaster.vercel.app</span> or associated
            domains).
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal flex items-center gap-2.5">
            <Eye className="h-5 w-5 text-gold" strokeWidth={1.5} />
            2. Information We Collect
          </h2>
          <p>To provide accurate prescription fitting and deliver your eyewear, we may collect:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>
              <strong>Contact Details:</strong> Full name, mobile phone number, and email address.
            </li>
            <li>
              <strong>Delivery Information:</strong> Shipping address, landmark, city, state, and
              postal PIN code.
            </li>
            <li>
              <strong>Optical &amp; Prescription Data:</strong> SPH, CYL, AXIS, ADD values, Pupillary
              Distance (PD), lens preference, and doctor prescription photos uploaded by you.
            </li>
            <li>
              <strong>Transaction &amp; Order Records:</strong> Order numbers, product selections,
              amounts paid, and payment reference tokens generated by our payment partner.
            </li>
            <li>
              <strong>Device &amp; Usage Data:</strong> IP address, browser type, and operating
              system for site analytics and fraud prevention.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal flex items-center gap-2.5">
            <Lock className="h-5 w-5 text-gold" strokeWidth={1.5} />
            3. Payment Security &amp; Financial Information
          </h2>
          <p>
            All online transactions on Lens Master are processed through certified, PCI-DSS compliant
            payment gateways (including <strong>Razorpay</strong>).
          </p>
          <p>
            <strong>We do not collect, capture, or store your credit/debit card numbers, CVV, or bank
            account passwords on our servers.</strong> All payment processing occurs on encrypted,
            secure bank servers.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal flex items-center gap-2.5">
            <FileText className="h-5 w-5 text-gold" strokeWidth={1.5} />
            4. How We Use Your Information
          </h2>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>To process, custom-cut, fit, and ship your eyewear and contact lens orders.</li>
            <li>
              To communicate order updates, shipping tracking, and prescription clarifications via
              WhatsApp, SMS, or email.
            </li>
            <li>To manage customer service inquiries, warranty claims, and optical consultations.</li>
            <li>To prevent fraudulent transactions and maintain platform security.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal">
            5. Sharing of Information
          </h2>
          <p>
            We do not sell, rent, or trade your personal data. We only share necessary information with
            trusted partners to provide our services:
          </p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>
              <strong>Logistics &amp; Courier Partners:</strong> Name, delivery address, and phone
              number to deliver your shipment across India.
            </li>
            <li>
              <strong>Payment Processors:</strong> Razorpay for secure checkout verification.
            </li>
            <li>
              <strong>Storefront Infrastructure:</strong> Shopify for live catalog inventory
              synchronization.
            </li>
            <li>
              <strong>Legal Obligations:</strong> If required by Indian law or government regulatory
              authorities.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal">
            6. Your Rights &amp; Data Access
          </h2>
          <p>
            You have the right to request a copy of your optical prescriptions on file, update your
            contact information, or request the deletion of your account history by reaching out to
            our team.
          </p>
        </section>

        <section className="space-y-3 border-t pt-8">
          <h2 className="font-display text-xl sm:text-2xl text-foreground font-normal">
            7. Contact Us
          </h2>
          <p>If you have any questions about this Privacy Policy, please contact us at:</p>
          <div className="bg-card p-5 rounded-2xl border space-y-1.5 text-sm text-foreground">
            <p className="font-semibold">Lens Master by The Swadesh</p>
            <p className="text-muted-foreground">
              B-51, Lal Kothi Shopping Centre, Jaipur, Rajasthan 302015
            </p>
            <p className="text-muted-foreground">
              Email:{" "}
              <a href="mailto:support@lensmaster.in" className="text-foreground underline">
                support@lensmaster.in
              </a>
            </p>
            <p className="text-muted-foreground">Phone / WhatsApp: +91 98292 30548 | 0141-4112904</p>
          </div>
        </section>
      </div>
    </div>
  );
}
