/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrderStatusRouteImport } from './routes/order-status'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPaytmInitiateRouteImport } from './routes/api/paytm/initiate'
import { Route as ApiRazorpayOrderRouteImport } from './routes/api/razorpay/order'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'
import { Route as ApiShopifyHealthRouteImport } from './routes/api/shopify/health'
import { Route as ApiShopifyProductsRouteImport } from './routes/api/shopify/products'
import { Route as ApiPublicImagesSplatRouteImport } from './routes/api/public/images/$'
import { Route as ApiPublicPaytmCallbackRouteImport } from './routes/api/public/paytm/callback'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaytmInitiateRoute = ApiPaytmInitiateRouteImport.update({
  id: '/api/paytm/initiate',
  path: '/api/paytm/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayOrderRoute = ApiRazorpayOrderRouteImport.update({
  id: '/api/razorpay/order',
  path: '/api/razorpay/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyHealthRoute = ApiShopifyHealthRouteImport.update({
  id: '/api/shopify/health',
  path: '/api/shopify/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyProductsRoute = ApiShopifyProductsRouteImport.update({
  id: '/api/shopify/products',
  path: '/api/shopify/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImagesSplatRoute = ApiPublicImagesSplatRouteImport.update({
  id: '/api/public/images/$',
  path: '/api/public/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaytmCallbackRoute = ApiPublicPaytmCallbackRouteImport.update({
  id: '/api/public/paytm/callback',
  path: '/api/public/paytm/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$handle': typeof ProductHandleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paytm/initiate': typeof ApiPaytmInitiateRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/shopify/health': typeof ApiShopifyHealthRoute
  '/api/shopify/products': typeof ApiShopifyProductsRoute
  '/api/public/images/$': typeof ApiPublicImagesSplatRoute
  '/api/public/paytm/callback': typeof ApiPublicPaytmCallbackRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$handle': typeof ProductHandleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paytm/initiate': typeof ApiPaytmInitiateRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/shopify/health': typeof ApiShopifyHealthRoute
  '/api/shopify/products': typeof ApiShopifyProductsRoute
  '/api/public/images/$': typeof ApiPublicImagesSplatRoute
  '/api/public/paytm/callback': typeof ApiPublicPaytmCallbackRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/order-status': typeof OrderStatusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/product/$handle': typeof ProductHandleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/paytm/initiate': typeof ApiPaytmInitiateRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/shopify/health': typeof ApiShopifyHealthRoute
  '/api/shopify/products': typeof ApiShopifyProductsRoute
  '/api/public/images/$': typeof ApiPublicImagesSplatRoute
  '/api/public/paytm/callback': typeof ApiPublicPaytmCallbackRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/brands'
    | '/checkout'
    | '/mcp'
    | '/order-status'
    | '/privacy-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/staff'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/product/$handle'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paytm/initiate'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/shopify/health'
    | '/api/shopify/products'
    | '/api/public/images/$'
    | '/api/public/paytm/callback'
    | '/api/public/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/brands'
    | '/checkout'
    | '/mcp'
    | '/order-status'
    | '/privacy-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/staff'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/product/$handle'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paytm/initiate'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/shopify/health'
    | '/api/shopify/products'
    | '/api/public/images/$'
    | '/api/public/paytm/callback'
    | '/api/public/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/brands'
    | '/checkout'
    | '/mcp'
    | '/order-status'
    | '/privacy-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/stores'
    | '/terms-and-conditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/staff'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/product/$handle'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/paytm/initiate'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/shopify/health'
    | '/api/shopify/products'
    | '/api/public/images/$'
    | '/api/public/paytm/callback'
    | '/api/public/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  CheckoutRoute: typeof CheckoutRoute
  McpRoute: typeof McpRoute
  OrderStatusRoute: typeof OrderStatusRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ProductHandleRoute: typeof ProductHandleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPaytmInitiateRoute: typeof ApiPaytmInitiateRoute
  ApiRazorpayOrderRoute: typeof ApiRazorpayOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
  ApiShopifyHealthRoute: typeof ApiShopifyHealthRoute
  ApiShopifyProductsRoute: typeof ApiShopifyProductsRoute
  ApiPublicImagesSplatRoute: typeof ApiPublicImagesSplatRoute
  ApiPublicPaytmCallbackRoute: typeof ApiPublicPaytmCallbackRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status': {
      id: '/order-status'
      path: '/order-status'
      fullPath: '/order-status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paytm/initiate': {
      id: '/api/paytm/initiate'
      path: '/api/paytm/initiate'
      fullPath: '/api/paytm/initiate'
      preLoaderRoute: typeof ApiPaytmInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/order': {
      id: '/api/razorpay/order'
      path: '/api/razorpay/order'
      fullPath: '/api/razorpay/order'
      preLoaderRoute: typeof ApiRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/health': {
      id: '/api/shopify/health'
      path: '/api/shopify/health'
      fullPath: '/api/shopify/health'
      preLoaderRoute: typeof ApiShopifyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/products': {
      id: '/api/shopify/products'
      path: '/api/shopify/products'
      fullPath: '/api/shopify/products'
      preLoaderRoute: typeof ApiShopifyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/images/$': {
      id: '/api/public/images/$'
      path: '/api/public/images/$'
      fullPath: '/api/public/images/$'
      preLoaderRoute: typeof ApiPublicImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paytm/callback': {
      id: '/api/public/paytm/callback'
      path: '/api/public/paytm/callback'
      fullPath: '/api/public/paytm/callback'
      preLoaderRoute: typeof ApiPublicPaytmCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminStaffRoute: typeof AdminStaffRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminStaffRoute: AdminStaffRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  CheckoutRoute: CheckoutRoute,
  McpRoute: McpRoute,
  OrderStatusRoute: OrderStatusRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ProductHandleRoute: ProductHandleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPaytmInitiateRoute: ApiPaytmInitiateRoute,
  ApiRazorpayOrderRoute: ApiRazorpayOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
  ApiShopifyHealthRoute: ApiShopifyHealthRoute,
  ApiShopifyProductsRoute: ApiShopifyProductsRoute,
  ApiPublicImagesSplatRoute: ApiPublicImagesSplatRoute,
  ApiPublicPaytmCallbackRoute: ApiPublicPaytmCallbackRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
