// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient(): ReturnType<typeof createClient<Database>> | null {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    (typeof import.meta !== 'undefined' ? import.meta.env?.['VITE_SUPABASE_URL'] : undefined) ||
    (typeof process !== 'undefined' ? process.env?.['SUPABASE_URL'] : undefined) ||
    (typeof process !== 'undefined' ? process.env?.['VITE_SUPABASE_URL'] : undefined);

  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' ? import.meta.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
    (typeof process !== 'undefined' ? process.env?.['SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
    (typeof process !== 'undefined' ? process.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'] : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    // Log but NEVER throw — throwing here crashes every SSR request.
    console.warn(`[Supabase] Missing env var(s): ${missing.join(', ')}. Supabase auth will be unavailable.`);
    return null;
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: typeof window !== 'undefined' ? brokeredPreviewStorage() : undefined,
        persistSession: typeof window !== 'undefined',
        autoRefreshToken: typeof window !== 'undefined',
      }
    });
  } catch (err) {
    console.warn('[Supabase] Failed to initialise client:', err);
    return null;
  }
}

let _supabase: ReturnType<typeof createClient<Database>> | null | undefined;

/**
 * Lazy singleton Supabase browser client.
 * Returns null when Supabase env vars are not configured (e.g. during SSR
 * without credentials). Always null-check before use.
 */
export function getSupabase(): ReturnType<typeof createClient<Database>> | null {
  if (_supabase === undefined) _supabase = createSupabaseClient();
  return _supabase;
}

// Proxy-based export kept for backwards compatibility with existing imports.
// When the client is null (missing env vars), every property access returns
// a no-op function so callers don't throw on SSR.
function makeNoop(): any {
  const noop: any = () => Promise.resolve({ data: null, error: new Error('Supabase not configured') });
  return new Proxy(noop, {
    get: () => makeNoop(),
    apply: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }),
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    if (_supabase === undefined) _supabase = createSupabaseClient();
    if (!_supabase) return makeNoop();
    return Reflect.get(_supabase, prop, receiver);
  },
});

